Repository intermine/intermine, pull requests merged in 2018-10, with the labels that each got.

#1841 Transfer sequences - update CDS to handle discontinous locations
  bio/postprocess/main/src/org/intermine/bio/postprocess/TransferSequences.java
  bio/postprocess/test/src/org/intermine/bio/postprocess/TransferSequencesTest.java
Labels: data

#1899 Allow specific versions of data sources to be used
  bio/build.gradle
  bio/core/src/main/resources/soClassName.properties
  bio/postprocess/build.gradle
  bio/sources/build.gradle
  bio/webapp/src/main/webapp/WEB-INF/soClassName.properties
  intermine/build.gradle
  plugin/build.gradle
  plugin/src/main/groovy/org/intermine/plugin/integrate/IntegratePlugin.groovy
  plugin/src/main/java/org/intermine/plugin/project/ProjectXmlBinding.java
  plugin/src/main/java/org/intermine/plugin/project/Source.java
Labels: bug, gradle

#1892 Add publication-fix
  bio/sources/update-publications/main/src/org/intermine/bio/dataconversion/EntrezPublicationsRetriever.java
Labels: enhancement, input-needed

#1911 Versioned postprocesses
  bio/sources/build.gradle
  plugin/src/main/groovy/org/intermine/plugin/dbmodel/DBModelPlugin.groovy
  plugin/src/main/groovy/org/intermine/plugin/dbmodel/DBModelUtils.groovy
  plugin/src/main/groovy/org/intermine/plugin/integrate/IntegratePlugin.groovy
  plugin/src/main/groovy/org/intermine/plugin/postprocess/PostProcessPlugin.groovy
  plugin/src/main/java/org/intermine/plugin/project/PostProcess.java
  plugin/src/main/java/org/intermine/plugin/project/ProjectXmlBinding.java
Labels: bug
