Repository intermine/intermine, pull requests merged in 2018-06, with the labels that each got.

#1765 Update URLGenerator.java to handle HTTPS sites
  intermine/web/main/src/org/intermine/web/util/URLGenerator.java
Labels: input-needed

#1753 I think I've got this in an up-to-date dev branch now. Allows null name field in the OBO.
  bio/core/main/src/org/intermine/bio/ontology/OboParser.java
Labels: input-needed

#1670 Json queries
  bio/core/main/src/org/intermine/bio/io/gaf/GAFRecord.java
  bio/tools/main/src/org/intermine/bio/web/export/GAFUtil.java
  bio/webapp/resources/webapp/WEB-INF/web-bio.xml
  bio/webapp/src/org/intermine/bio/webservice/BioQueryService.java
  intermine/api/main/src/org/intermine/api/query/codegen/WebserviceJavaCodeGenerator.java
  intermine/api/test/resources/org/intermine/api/query/codegen/loop-template.js.expected
  intermine/api/test/resources/org/intermine/api/query/codegen/loopeq-constraint.js.expected
  intermine/api/test/resources/org/intermine/api/query/codegen/loopne-constraint.js.expected
  intermine/api/test/resources/org/intermine/api/query/codegen/multiple-constraints.js.expected
  intermine/api/test/resources/org/intermine/api/query/codegen/neloop-template.js.expected
  intermine/pathquery/main/src/org/intermine/pathquery/JSONQueryHandler.java
  intermine/pathquery/main/src/org/intermine/pathquery/PathConstraintAttribute.java
  intermine/pathquery/main/src/org/intermine/pathquery/PathQuery.java
  intermine/pathquery/main/src/org/intermine/pathquery/PathQueryBinding.java
  intermine/pathquery/main/src/org/intermine/template/xml/TemplateQueryBinding.java
  intermine/pathquery/test/resources/PathQueryBindingTest.xml
  intermine/pathquery/test/src/org/intermine/pathquery/PathQueryBindingTest.java
  intermine/web/main/.classpath
  intermine/web/main/lib/google-collections-1.0-rc2.jar
  intermine/web/main/lib/org.everit.json.schema-1.5.1.jar
  intermine/web/main/src/org/intermine/webservice/server/clob/SequenceService.java
  intermine/web/main/src/org/intermine/webservice/server/query/AbstractQueryService.java
  intermine/web/main/src/org/intermine/webservice/server/query/QueryToListService.java
  intermine/web/main/src/org/intermine/webservice/server/query/QueryUploadService.java
  intermine/web/main/src/org/intermine/webservice/server/query/result/PathQueryBuilder.java
  intermine/web/main/src/org/intermine/webservice/server/query/result/PathQueryBuilderForJSONObj.java
  intermine/web/main/src/org/intermine/webservice/server/template/TemplateUploadService.java
  intermine/web/test/.classpath
  intermine/web/test/resources/query.xsd
  intermine/web/test/src/org/intermine/webservice/server/query/result/PathQueryBuilderTest.java
  intermine/webapp/main/resources/webapp/WEB-INF/web.xml
  intermine/webapp/main/resources/webapp/webservice/query.schema
Labels: enhancement, please-test

#1817 Remove obsolete upgrade check
  intermine/web/main/src/org/intermine/web/struts/InitialiserPlugin.java
Labels: enhancement

#1772 Biojava
  bio/core/main/.classpath
  bio/core/main/lib/biojava-1.7.1.jar
  bio/core/main/lib/biojava-core-4.2.0.jar
  bio/core/main/lib/biojava3-alignment-3.0.5.jar
  bio/core/main/lib/biojava3-core-3.0.5.jar
  bio/core/main/lib/biojava3-genome-3.0.5.jar
  bio/core/main/lib/biojava3-structure-3.0.5.jar
  bio/skeletons/mine/dbmodel/resources/objectstoresummary.config.properties
  bio/sources/fasta/.classpath
  bio/sources/fasta/main/src/org/intermine/bio/dataconversion/FastaLoaderTask.java
  bio/sources/fasta/main/src/org/intermine/bio/dataconversion/FlyBaseCDSFastaLoaderTask.java
  bio/sources/fasta/main/src/org/intermine/bio/dataconversion/FlyBaseUTRFastaLoaderTask.java
  bio/sources/fasta/main/src/org/intermine/bio/dataconversion/NCBIFastaLoaderTask.java
  bio/sources/fasta/main/src/org/intermine/bio/dataconversion/UniProtFastaLoaderTask.java
  bio/sources/fasta/test/src/org/intermine/bio/dataconversion/FastaLoaderTaskTest.java
  bio/sources/fasta/test/src/org/intermine/bio/dataconversion/FlyBaseCDSFastaLoaderTaskTest.java
  bio/sources/fasta/test/src/org/intermine/bio/dataconversion/FlyBaseUTRFastaLoaderTaskTest.java
  bio/sources/fasta/test/src/org/intermine/bio/dataconversion/NCBIFastaLoaderTaskTest.java
  bio/sources/fasta/test/src/org/intermine/bio/dataconversion/UniProtFastaLoaderTaskTest.java
  bio/webapp/.classpath
  bio/webapp/lib/biojava-1.7.1.jar
  bio/webapp/lib/biojava-core-4.2.0.jar
  bio/webapp/lib/biojava-genome-4.2.0.jar
  bio/webapp/lib/biojava-ontology-4.2.0.jar
  bio/webapp/src/org/intermine/bio/web/biojava/BioSequence.java
  bio/webapp/src/org/intermine/bio/web/biojava/BioSequenceFactory.java
  bio/webapp/src/org/intermine/bio/web/export/GenomicRegionSequenceExporter.java
  bio/webapp/src/org/intermine/bio/web/export/ResidueFieldExporter.java
  bio/webapp/src/org/intermine/bio/web/export/SequenceExporter.java
  bio/webapp/src/org/intermine/bio/web/struts/SequenceExportAction.java
  flymine/dbmodel/resources/objectstoresummary.config.properties
  humanmine/dbmodel/resources/objectstoresummary.config.properties
Labels: in-progress
