Repository intermine/intermine, pull requests merged in 2019-02, with the labels that each got.

#1929 add does not contain op.
  intermine/api/src/main/java/org/intermine/api/query/MainHelper.java
Labels: bug, input-needed

#1923 GFF: pass in the record to the seq handler
  bio/core/src/main/java/org/intermine/bio/dataconversion/GFF3Converter.java
  bio/core/src/main/java/org/intermine/bio/dataconversion/GFF3SeqHandler.java
  bio/sources/fly/uberfly/.checkstyle
  bio/sources/fly/uberfly/.classpath
  bio/sources/fly/uberfly/.project
  bio/sources/fly/uberfly/build.xml
  bio/sources/fly/uberfly/main/build.xml
  bio/sources/fly/uberfly/main/lib/.gitignore
  bio/sources/fly/uberfly/main/project.properties
  bio/sources/fly/uberfly/main/resources/.gitignore
  bio/sources/fly/uberfly/main/src/org/intermine/bio/dataconversion/UberflyConverter.java
  bio/sources/fly/uberfly/project.properties
  bio/sources/fly/uberfly/resources/uberfly_keys.properties
  bio/sources/fly/uberfly/test/build.xml
  bio/sources/fly/uberfly/test/project.properties
  bio/sources/fly/uberfly/test/resources/UberflyConverterTest_tgt.xml
  bio/sources/fly/uberfly/test/resources/data/SRX193500.tsv
  bio/sources/fly/uberfly/test/resources/metadata.tsv
  bio/sources/fly/uberfly/test/src/org/intermine/bio/dataconversion/UberflyConverterTest.java
  bio/sources/fly/uberfly/uberfly_additions.xml
Labels: enhancement, please-test

#1930 add a end point to only return system templates.
  intermine/api/src/main/java/org/intermine/api/template/TemplateManager.java
  intermine/webapp/src/main/java/org/intermine/web/logic/Constants.java
  intermine/webapp/src/main/java/org/intermine/webservice/server/template/SystemTemplatesService.java
  intermine/webapp/src/main/webapp/WEB-INF/web.xml
Labels: please-test

#1924 GFF: add header
  bio/core/src/main/java/org/intermine/bio/io/gff3/GFF3Parser.java
  bio/core/src/main/java/org/intermine/bio/io/gff3/GFF3Record.java
Labels: enhancement, please-test

#1933 Template tags webservice
  intermine/webapp/src/main/java/org/intermine/web/logic/Constants.java
  intermine/webapp/src/main/java/org/intermine/webservice/server/template/TemplateTagAddingService.java
  intermine/webapp/src/main/java/org/intermine/webservice/server/template/TemplateTagRemovalService.java
  intermine/webapp/src/main/java/org/intermine/webservice/server/template/TemplateTagService.java
  intermine/webapp/src/main/webapp/WEB-INF/web.xml
Labels: enhancement, please-test

#2002 modify SolrIndexHandler to support newer Solr versions
  intermine/api/src/main/java/org/intermine/api/searchengine/solr/SolrIndexHandler.java
  intermine/api/src/main/java/org/intermine/api/searchengine/solr/SolrObjectHandler.java
  intermine/webapp/src/main/java/org/intermine/web/autocompletion/AutoCompleter.java
Labels: enhancement, please-test
